<?php
/**
 * ClinicalAttributesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * cBioPortal web Public API [Beta]
 *
 * A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.
 *
 * OpenAPI spec version: 1.0
 * Contact: cbioportal@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ClinicalAttributesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ClinicalAttributesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for fetchClinicalAttributesUsingPOST
     *
     * Fetch clinical attributes.
     *
     */
    public function testFetchClinicalAttributesUsingPOST()
    {
    }

    /**
     * Test case for getAllClinicalAttributesInStudyUsingGET
     *
     * Get all clinical attributes in the specified study.
     *
     */
    public function testGetAllClinicalAttributesInStudyUsingGET()
    {
    }

    /**
     * Test case for getAllClinicalAttributesUsingGET
     *
     * Get all clinical attributes.
     *
     */
    public function testGetAllClinicalAttributesUsingGET()
    {
    }

    /**
     * Test case for getClinicalAttributeInStudyUsingGET
     *
     * Get specified clinical attribute.
     *
     */
    public function testGetClinicalAttributeInStudyUsingGET()
    {
    }
}
