<?php
/**
 * ClinicalData
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * cBioPortal web Public API [Beta]
 *
 * A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.
 *
 * OpenAPI spec version: 1.0
 * Contact: cbioportal@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ClinicalData Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ClinicalData implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ClinicalData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'clinical_attribute' => '\Swagger\Client\Model\ClinicalAttribute',
        'clinical_attribute_id' => 'string',
        'patient_id' => 'string',
        'sample_id' => 'string',
        'study_id' => 'string',
        'unique_patient_key' => 'string',
        'unique_sample_key' => 'string',
        'value' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'clinical_attribute' => null,
        'clinical_attribute_id' => null,
        'patient_id' => null,
        'sample_id' => null,
        'study_id' => null,
        'unique_patient_key' => null,
        'unique_sample_key' => null,
        'value' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'clinical_attribute' => 'clinicalAttribute',
        'clinical_attribute_id' => 'clinicalAttributeId',
        'patient_id' => 'patientId',
        'sample_id' => 'sampleId',
        'study_id' => 'studyId',
        'unique_patient_key' => 'uniquePatientKey',
        'unique_sample_key' => 'uniqueSampleKey',
        'value' => 'value'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'clinical_attribute' => 'setClinicalAttribute',
        'clinical_attribute_id' => 'setClinicalAttributeId',
        'patient_id' => 'setPatientId',
        'sample_id' => 'setSampleId',
        'study_id' => 'setStudyId',
        'unique_patient_key' => 'setUniquePatientKey',
        'unique_sample_key' => 'setUniqueSampleKey',
        'value' => 'setValue'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'clinical_attribute' => 'getClinicalAttribute',
        'clinical_attribute_id' => 'getClinicalAttributeId',
        'patient_id' => 'getPatientId',
        'sample_id' => 'getSampleId',
        'study_id' => 'getStudyId',
        'unique_patient_key' => 'getUniquePatientKey',
        'unique_sample_key' => 'getUniqueSampleKey',
        'value' => 'getValue'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['clinical_attribute'] = isset($data['clinical_attribute']) ? $data['clinical_attribute'] : null;
        $this->container['clinical_attribute_id'] = isset($data['clinical_attribute_id']) ? $data['clinical_attribute_id'] : null;
        $this->container['patient_id'] = isset($data['patient_id']) ? $data['patient_id'] : null;
        $this->container['sample_id'] = isset($data['sample_id']) ? $data['sample_id'] : null;
        $this->container['study_id'] = isset($data['study_id']) ? $data['study_id'] : null;
        $this->container['unique_patient_key'] = isset($data['unique_patient_key']) ? $data['unique_patient_key'] : null;
        $this->container['unique_sample_key'] = isset($data['unique_sample_key']) ? $data['unique_sample_key'] : null;
        $this->container['value'] = isset($data['value']) ? $data['value'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['clinical_attribute_id'] === null) {
            $invalidProperties[] = "'clinical_attribute_id' can't be null";
        }
        if ($this->container['patient_id'] === null) {
            $invalidProperties[] = "'patient_id' can't be null";
        }
        if ($this->container['study_id'] === null) {
            $invalidProperties[] = "'study_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets clinical_attribute
     *
     * @return \Swagger\Client\Model\ClinicalAttribute
     */
    public function getClinicalAttribute()
    {
        return $this->container['clinical_attribute'];
    }

    /**
     * Sets clinical_attribute
     *
     * @param \Swagger\Client\Model\ClinicalAttribute $clinical_attribute clinical_attribute
     *
     * @return $this
     */
    public function setClinicalAttribute($clinical_attribute)
    {
        $this->container['clinical_attribute'] = $clinical_attribute;

        return $this;
    }

    /**
     * Gets clinical_attribute_id
     *
     * @return string
     */
    public function getClinicalAttributeId()
    {
        return $this->container['clinical_attribute_id'];
    }

    /**
     * Sets clinical_attribute_id
     *
     * @param string $clinical_attribute_id clinical_attribute_id
     *
     * @return $this
     */
    public function setClinicalAttributeId($clinical_attribute_id)
    {
        $this->container['clinical_attribute_id'] = $clinical_attribute_id;

        return $this;
    }

    /**
     * Gets patient_id
     *
     * @return string
     */
    public function getPatientId()
    {
        return $this->container['patient_id'];
    }

    /**
     * Sets patient_id
     *
     * @param string $patient_id patient_id
     *
     * @return $this
     */
    public function setPatientId($patient_id)
    {
        $this->container['patient_id'] = $patient_id;

        return $this;
    }

    /**
     * Gets sample_id
     *
     * @return string
     */
    public function getSampleId()
    {
        return $this->container['sample_id'];
    }

    /**
     * Sets sample_id
     *
     * @param string $sample_id sample_id
     *
     * @return $this
     */
    public function setSampleId($sample_id)
    {
        $this->container['sample_id'] = $sample_id;

        return $this;
    }

    /**
     * Gets study_id
     *
     * @return string
     */
    public function getStudyId()
    {
        return $this->container['study_id'];
    }

    /**
     * Sets study_id
     *
     * @param string $study_id study_id
     *
     * @return $this
     */
    public function setStudyId($study_id)
    {
        $this->container['study_id'] = $study_id;

        return $this;
    }

    /**
     * Gets unique_patient_key
     *
     * @return string
     */
    public function getUniquePatientKey()
    {
        return $this->container['unique_patient_key'];
    }

    /**
     * Sets unique_patient_key
     *
     * @param string $unique_patient_key unique_patient_key
     *
     * @return $this
     */
    public function setUniquePatientKey($unique_patient_key)
    {
        $this->container['unique_patient_key'] = $unique_patient_key;

        return $this;
    }

    /**
     * Gets unique_sample_key
     *
     * @return string
     */
    public function getUniqueSampleKey()
    {
        return $this->container['unique_sample_key'];
    }

    /**
     * Sets unique_sample_key
     *
     * @param string $unique_sample_key unique_sample_key
     *
     * @return $this
     */
    public function setUniqueSampleKey($unique_sample_key)
    {
        $this->container['unique_sample_key'] = $unique_sample_key;

        return $this;
    }

    /**
     * Gets value
     *
     * @return string
     */
    public function getValue()
    {
        return $this->container['value'];
    }

    /**
     * Sets value
     *
     * @param string $value value
     *
     * @return $this
     */
    public function setValue($value)
    {
        $this->container['value'] = $value;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


