<?php
/**
 * SampleFilter
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * cBioPortal web Public API [Beta]
 *
 * A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.
 *
 * OpenAPI spec version: 1.0
 * Contact: cbioportal@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * SampleFilter Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SampleFilter implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SampleFilter';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'sample_identifiers' => '\Swagger\Client\Model\SampleIdentifier[]',
        'sample_list_ids' => 'string[]',
        'unique_sample_keys' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'sample_identifiers' => null,
        'sample_list_ids' => null,
        'unique_sample_keys' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sample_identifiers' => 'sampleIdentifiers',
        'sample_list_ids' => 'sampleListIds',
        'unique_sample_keys' => 'uniqueSampleKeys'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sample_identifiers' => 'setSampleIdentifiers',
        'sample_list_ids' => 'setSampleListIds',
        'unique_sample_keys' => 'setUniqueSampleKeys'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sample_identifiers' => 'getSampleIdentifiers',
        'sample_list_ids' => 'getSampleListIds',
        'unique_sample_keys' => 'getUniqueSampleKeys'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['sample_identifiers'] = isset($data['sample_identifiers']) ? $data['sample_identifiers'] : null;
        $this->container['sample_list_ids'] = isset($data['sample_list_ids']) ? $data['sample_list_ids'] : null;
        $this->container['unique_sample_keys'] = isset($data['unique_sample_keys']) ? $data['unique_sample_keys'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sample_identifiers
     *
     * @return \Swagger\Client\Model\SampleIdentifier[]
     */
    public function getSampleIdentifiers()
    {
        return $this->container['sample_identifiers'];
    }

    /**
     * Sets sample_identifiers
     *
     * @param \Swagger\Client\Model\SampleIdentifier[] $sample_identifiers sample_identifiers
     *
     * @return $this
     */
    public function setSampleIdentifiers($sample_identifiers)
    {
        $this->container['sample_identifiers'] = $sample_identifiers;

        return $this;
    }

    /**
     * Gets sample_list_ids
     *
     * @return string[]
     */
    public function getSampleListIds()
    {
        return $this->container['sample_list_ids'];
    }

    /**
     * Sets sample_list_ids
     *
     * @param string[] $sample_list_ids sample_list_ids
     *
     * @return $this
     */
    public function setSampleListIds($sample_list_ids)
    {
        $this->container['sample_list_ids'] = $sample_list_ids;

        return $this;
    }

    /**
     * Gets unique_sample_keys
     *
     * @return string[]
     */
    public function getUniqueSampleKeys()
    {
        return $this->container['unique_sample_keys'];
    }

    /**
     * Sets unique_sample_keys
     *
     * @param string[] $unique_sample_keys unique_sample_keys
     *
     * @return $this
     */
    public function setUniqueSampleKeys($unique_sample_keys)
    {
        $this->container['unique_sample_keys'] = $unique_sample_keys;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


