<?php
/**
 * CancerTypesApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * cBioPortal web Public API [Beta]
 *
 * A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.
 *
 * OpenAPI spec version: 1.0
 * Contact: cbioportal@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * CancerTypesApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CancerTypesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getAllCancerTypesUsingGET
     *
     * Get all cancer types
     *
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\TypeOfCancer[]
     */
    public function getAllCancerTypesUsingGET($direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        list($response) = $this->getAllCancerTypesUsingGETWithHttpInfo($direction, $page_number, $page_size, $projection, $sort_by);
        return $response;
    }

    /**
     * Operation getAllCancerTypesUsingGETWithHttpInfo
     *
     * Get all cancer types
     *
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\TypeOfCancer[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllCancerTypesUsingGETWithHttpInfo($direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        $returnType = '\Swagger\Client\Model\TypeOfCancer[]';
        $request = $this->getAllCancerTypesUsingGETRequest($direction, $page_number, $page_size, $projection, $sort_by);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\TypeOfCancer[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAllCancerTypesUsingGETAsync
     *
     * Get all cancer types
     *
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllCancerTypesUsingGETAsync($direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        return $this->getAllCancerTypesUsingGETAsyncWithHttpInfo($direction, $page_number, $page_size, $projection, $sort_by)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllCancerTypesUsingGETAsyncWithHttpInfo
     *
     * Get all cancer types
     *
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllCancerTypesUsingGETAsyncWithHttpInfo($direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        $returnType = '\Swagger\Client\Model\TypeOfCancer[]';
        $request = $this->getAllCancerTypesUsingGETRequest($direction, $page_number, $page_size, $projection, $sort_by);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllCancerTypesUsingGET'
     *
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAllCancerTypesUsingGETRequest($direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        if ($page_number !== null && $page_number < 0) {
            throw new \InvalidArgumentException('invalid value for "$page_number" when calling CancerTypesApi.getAllCancerTypesUsingGET, must be bigger than or equal to 0.');
        }

        if ($page_size !== null && $page_size > 10000000) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling CancerTypesApi.getAllCancerTypesUsingGET, must be smaller than or equal to 10000000.');
        }
        if ($page_size !== null && $page_size < 1) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling CancerTypesApi.getAllCancerTypesUsingGET, must be bigger than or equal to 1.');
        }


        $resourcePath = '/cancer-types';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($direction !== null) {
            $queryParams['direction'] = ObjectSerializer::toQueryValue($direction);
        }
        // query params
        if ($page_number !== null) {
            $queryParams['pageNumber'] = ObjectSerializer::toQueryValue($page_number);
        }
        // query params
        if ($page_size !== null) {
            $queryParams['pageSize'] = ObjectSerializer::toQueryValue($page_size);
        }
        // query params
        if ($projection !== null) {
            $queryParams['projection'] = ObjectSerializer::toQueryValue($projection);
        }
        // query params
        if ($sort_by !== null) {
            $queryParams['sortBy'] = ObjectSerializer::toQueryValue($sort_by);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCancerTypeUsingGET
     *
     * Get a cancer type
     *
     * @param  string $cancer_type_id Cancer Type ID e.g. acc (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\TypeOfCancer
     */
    public function getCancerTypeUsingGET($cancer_type_id)
    {
        list($response) = $this->getCancerTypeUsingGETWithHttpInfo($cancer_type_id);
        return $response;
    }

    /**
     * Operation getCancerTypeUsingGETWithHttpInfo
     *
     * Get a cancer type
     *
     * @param  string $cancer_type_id Cancer Type ID e.g. acc (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\TypeOfCancer, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCancerTypeUsingGETWithHttpInfo($cancer_type_id)
    {
        $returnType = '\Swagger\Client\Model\TypeOfCancer';
        $request = $this->getCancerTypeUsingGETRequest($cancer_type_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\TypeOfCancer',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getCancerTypeUsingGETAsync
     *
     * Get a cancer type
     *
     * @param  string $cancer_type_id Cancer Type ID e.g. acc (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCancerTypeUsingGETAsync($cancer_type_id)
    {
        return $this->getCancerTypeUsingGETAsyncWithHttpInfo($cancer_type_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCancerTypeUsingGETAsyncWithHttpInfo
     *
     * Get a cancer type
     *
     * @param  string $cancer_type_id Cancer Type ID e.g. acc (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCancerTypeUsingGETAsyncWithHttpInfo($cancer_type_id)
    {
        $returnType = '\Swagger\Client\Model\TypeOfCancer';
        $request = $this->getCancerTypeUsingGETRequest($cancer_type_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCancerTypeUsingGET'
     *
     * @param  string $cancer_type_id Cancer Type ID e.g. acc (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getCancerTypeUsingGETRequest($cancer_type_id)
    {
        // verify the required parameter 'cancer_type_id' is set
        if ($cancer_type_id === null || (is_array($cancer_type_id) && count($cancer_type_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cancer_type_id when calling getCancerTypeUsingGET'
            );
        }

        $resourcePath = '/cancer-types/{cancerTypeId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($cancer_type_id !== null) {
            $resourcePath = str_replace(
                '{' . 'cancerTypeId' . '}',
                ObjectSerializer::toPathValue($cancer_type_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
