<?php
/**
 * ClinicalDataApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * cBioPortal web Public API [Beta]
 *
 * A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.
 *
 * OpenAPI spec version: 1.0
 * Contact: cbioportal@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * ClinicalDataApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ClinicalDataApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation fetchAllClinicalDataInStudyUsingPOST
     *
     * Fetch clinical data by patient IDs or sample IDs (specific study)
     *
     * @param  \Swagger\Client\Model\ClinicalDataSingleStudyFilter $clinical_data_single_study_filter List of patient or sample IDs and attribute IDs (required)
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $clinical_data_type Type of the clinical data (optional, default to SAMPLE)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ClinicalData[]
     */
    public function fetchAllClinicalDataInStudyUsingPOST($clinical_data_single_study_filter, $study_id, $clinical_data_type = 'SAMPLE', $projection = 'SUMMARY')
    {
        list($response) = $this->fetchAllClinicalDataInStudyUsingPOSTWithHttpInfo($clinical_data_single_study_filter, $study_id, $clinical_data_type, $projection);
        return $response;
    }

    /**
     * Operation fetchAllClinicalDataInStudyUsingPOSTWithHttpInfo
     *
     * Fetch clinical data by patient IDs or sample IDs (specific study)
     *
     * @param  \Swagger\Client\Model\ClinicalDataSingleStudyFilter $clinical_data_single_study_filter List of patient or sample IDs and attribute IDs (required)
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $clinical_data_type Type of the clinical data (optional, default to SAMPLE)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ClinicalData[], HTTP status code, HTTP response headers (array of strings)
     */
    public function fetchAllClinicalDataInStudyUsingPOSTWithHttpInfo($clinical_data_single_study_filter, $study_id, $clinical_data_type = 'SAMPLE', $projection = 'SUMMARY')
    {
        $returnType = '\Swagger\Client\Model\ClinicalData[]';
        $request = $this->fetchAllClinicalDataInStudyUsingPOSTRequest($clinical_data_single_study_filter, $study_id, $clinical_data_type, $projection);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ClinicalData[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation fetchAllClinicalDataInStudyUsingPOSTAsync
     *
     * Fetch clinical data by patient IDs or sample IDs (specific study)
     *
     * @param  \Swagger\Client\Model\ClinicalDataSingleStudyFilter $clinical_data_single_study_filter List of patient or sample IDs and attribute IDs (required)
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $clinical_data_type Type of the clinical data (optional, default to SAMPLE)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function fetchAllClinicalDataInStudyUsingPOSTAsync($clinical_data_single_study_filter, $study_id, $clinical_data_type = 'SAMPLE', $projection = 'SUMMARY')
    {
        return $this->fetchAllClinicalDataInStudyUsingPOSTAsyncWithHttpInfo($clinical_data_single_study_filter, $study_id, $clinical_data_type, $projection)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation fetchAllClinicalDataInStudyUsingPOSTAsyncWithHttpInfo
     *
     * Fetch clinical data by patient IDs or sample IDs (specific study)
     *
     * @param  \Swagger\Client\Model\ClinicalDataSingleStudyFilter $clinical_data_single_study_filter List of patient or sample IDs and attribute IDs (required)
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $clinical_data_type Type of the clinical data (optional, default to SAMPLE)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function fetchAllClinicalDataInStudyUsingPOSTAsyncWithHttpInfo($clinical_data_single_study_filter, $study_id, $clinical_data_type = 'SAMPLE', $projection = 'SUMMARY')
    {
        $returnType = '\Swagger\Client\Model\ClinicalData[]';
        $request = $this->fetchAllClinicalDataInStudyUsingPOSTRequest($clinical_data_single_study_filter, $study_id, $clinical_data_type, $projection);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'fetchAllClinicalDataInStudyUsingPOST'
     *
     * @param  \Swagger\Client\Model\ClinicalDataSingleStudyFilter $clinical_data_single_study_filter List of patient or sample IDs and attribute IDs (required)
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $clinical_data_type Type of the clinical data (optional, default to SAMPLE)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function fetchAllClinicalDataInStudyUsingPOSTRequest($clinical_data_single_study_filter, $study_id, $clinical_data_type = 'SAMPLE', $projection = 'SUMMARY')
    {
        // verify the required parameter 'clinical_data_single_study_filter' is set
        if ($clinical_data_single_study_filter === null || (is_array($clinical_data_single_study_filter) && count($clinical_data_single_study_filter) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $clinical_data_single_study_filter when calling fetchAllClinicalDataInStudyUsingPOST'
            );
        }
        // verify the required parameter 'study_id' is set
        if ($study_id === null || (is_array($study_id) && count($study_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $study_id when calling fetchAllClinicalDataInStudyUsingPOST'
            );
        }

        $resourcePath = '/studies/{studyId}/clinical-data/fetch';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($clinical_data_type !== null) {
            $queryParams['clinicalDataType'] = ObjectSerializer::toQueryValue($clinical_data_type);
        }
        // query params
        if ($projection !== null) {
            $queryParams['projection'] = ObjectSerializer::toQueryValue($projection);
        }

        // path params
        if ($study_id !== null) {
            $resourcePath = str_replace(
                '{' . 'studyId' . '}',
                ObjectSerializer::toPathValue($study_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($clinical_data_single_study_filter)) {
            $_tempBody = $clinical_data_single_study_filter;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation fetchClinicalDataUsingPOST
     *
     * Fetch clinical data by patient IDs or sample IDs (all studies)
     *
     * @param  \Swagger\Client\Model\ClinicalDataMultiStudyFilter $clinical_data_multi_study_filter List of patient or sample identifiers and attribute IDs (required)
     * @param  string $clinical_data_type Type of the clinical data (optional, default to SAMPLE)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ClinicalData[]
     */
    public function fetchClinicalDataUsingPOST($clinical_data_multi_study_filter, $clinical_data_type = 'SAMPLE', $projection = 'SUMMARY')
    {
        list($response) = $this->fetchClinicalDataUsingPOSTWithHttpInfo($clinical_data_multi_study_filter, $clinical_data_type, $projection);
        return $response;
    }

    /**
     * Operation fetchClinicalDataUsingPOSTWithHttpInfo
     *
     * Fetch clinical data by patient IDs or sample IDs (all studies)
     *
     * @param  \Swagger\Client\Model\ClinicalDataMultiStudyFilter $clinical_data_multi_study_filter List of patient or sample identifiers and attribute IDs (required)
     * @param  string $clinical_data_type Type of the clinical data (optional, default to SAMPLE)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ClinicalData[], HTTP status code, HTTP response headers (array of strings)
     */
    public function fetchClinicalDataUsingPOSTWithHttpInfo($clinical_data_multi_study_filter, $clinical_data_type = 'SAMPLE', $projection = 'SUMMARY')
    {
        $returnType = '\Swagger\Client\Model\ClinicalData[]';
        $request = $this->fetchClinicalDataUsingPOSTRequest($clinical_data_multi_study_filter, $clinical_data_type, $projection);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ClinicalData[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation fetchClinicalDataUsingPOSTAsync
     *
     * Fetch clinical data by patient IDs or sample IDs (all studies)
     *
     * @param  \Swagger\Client\Model\ClinicalDataMultiStudyFilter $clinical_data_multi_study_filter List of patient or sample identifiers and attribute IDs (required)
     * @param  string $clinical_data_type Type of the clinical data (optional, default to SAMPLE)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function fetchClinicalDataUsingPOSTAsync($clinical_data_multi_study_filter, $clinical_data_type = 'SAMPLE', $projection = 'SUMMARY')
    {
        return $this->fetchClinicalDataUsingPOSTAsyncWithHttpInfo($clinical_data_multi_study_filter, $clinical_data_type, $projection)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation fetchClinicalDataUsingPOSTAsyncWithHttpInfo
     *
     * Fetch clinical data by patient IDs or sample IDs (all studies)
     *
     * @param  \Swagger\Client\Model\ClinicalDataMultiStudyFilter $clinical_data_multi_study_filter List of patient or sample identifiers and attribute IDs (required)
     * @param  string $clinical_data_type Type of the clinical data (optional, default to SAMPLE)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function fetchClinicalDataUsingPOSTAsyncWithHttpInfo($clinical_data_multi_study_filter, $clinical_data_type = 'SAMPLE', $projection = 'SUMMARY')
    {
        $returnType = '\Swagger\Client\Model\ClinicalData[]';
        $request = $this->fetchClinicalDataUsingPOSTRequest($clinical_data_multi_study_filter, $clinical_data_type, $projection);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'fetchClinicalDataUsingPOST'
     *
     * @param  \Swagger\Client\Model\ClinicalDataMultiStudyFilter $clinical_data_multi_study_filter List of patient or sample identifiers and attribute IDs (required)
     * @param  string $clinical_data_type Type of the clinical data (optional, default to SAMPLE)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function fetchClinicalDataUsingPOSTRequest($clinical_data_multi_study_filter, $clinical_data_type = 'SAMPLE', $projection = 'SUMMARY')
    {
        // verify the required parameter 'clinical_data_multi_study_filter' is set
        if ($clinical_data_multi_study_filter === null || (is_array($clinical_data_multi_study_filter) && count($clinical_data_multi_study_filter) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $clinical_data_multi_study_filter when calling fetchClinicalDataUsingPOST'
            );
        }

        $resourcePath = '/clinical-data/fetch';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($clinical_data_type !== null) {
            $queryParams['clinicalDataType'] = ObjectSerializer::toQueryValue($clinical_data_type);
        }
        // query params
        if ($projection !== null) {
            $queryParams['projection'] = ObjectSerializer::toQueryValue($projection);
        }


        // body params
        $_tempBody = null;
        if (isset($clinical_data_multi_study_filter)) {
            $_tempBody = $clinical_data_multi_study_filter;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAllClinicalDataInStudyUsingGET
     *
     * Get all clinical data in a study
     *
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $attribute_id Attribute ID e.g. CANCER_TYPE (optional)
     * @param  string $clinical_data_type Type of the clinical data (optional, default to SAMPLE)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ClinicalData[]
     */
    public function getAllClinicalDataInStudyUsingGET($study_id, $attribute_id = null, $clinical_data_type = 'SAMPLE', $direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        list($response) = $this->getAllClinicalDataInStudyUsingGETWithHttpInfo($study_id, $attribute_id, $clinical_data_type, $direction, $page_number, $page_size, $projection, $sort_by);
        return $response;
    }

    /**
     * Operation getAllClinicalDataInStudyUsingGETWithHttpInfo
     *
     * Get all clinical data in a study
     *
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $attribute_id Attribute ID e.g. CANCER_TYPE (optional)
     * @param  string $clinical_data_type Type of the clinical data (optional, default to SAMPLE)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ClinicalData[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllClinicalDataInStudyUsingGETWithHttpInfo($study_id, $attribute_id = null, $clinical_data_type = 'SAMPLE', $direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        $returnType = '\Swagger\Client\Model\ClinicalData[]';
        $request = $this->getAllClinicalDataInStudyUsingGETRequest($study_id, $attribute_id, $clinical_data_type, $direction, $page_number, $page_size, $projection, $sort_by);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ClinicalData[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAllClinicalDataInStudyUsingGETAsync
     *
     * Get all clinical data in a study
     *
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $attribute_id Attribute ID e.g. CANCER_TYPE (optional)
     * @param  string $clinical_data_type Type of the clinical data (optional, default to SAMPLE)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllClinicalDataInStudyUsingGETAsync($study_id, $attribute_id = null, $clinical_data_type = 'SAMPLE', $direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        return $this->getAllClinicalDataInStudyUsingGETAsyncWithHttpInfo($study_id, $attribute_id, $clinical_data_type, $direction, $page_number, $page_size, $projection, $sort_by)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllClinicalDataInStudyUsingGETAsyncWithHttpInfo
     *
     * Get all clinical data in a study
     *
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $attribute_id Attribute ID e.g. CANCER_TYPE (optional)
     * @param  string $clinical_data_type Type of the clinical data (optional, default to SAMPLE)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllClinicalDataInStudyUsingGETAsyncWithHttpInfo($study_id, $attribute_id = null, $clinical_data_type = 'SAMPLE', $direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        $returnType = '\Swagger\Client\Model\ClinicalData[]';
        $request = $this->getAllClinicalDataInStudyUsingGETRequest($study_id, $attribute_id, $clinical_data_type, $direction, $page_number, $page_size, $projection, $sort_by);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllClinicalDataInStudyUsingGET'
     *
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $attribute_id Attribute ID e.g. CANCER_TYPE (optional)
     * @param  string $clinical_data_type Type of the clinical data (optional, default to SAMPLE)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAllClinicalDataInStudyUsingGETRequest($study_id, $attribute_id = null, $clinical_data_type = 'SAMPLE', $direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        // verify the required parameter 'study_id' is set
        if ($study_id === null || (is_array($study_id) && count($study_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $study_id when calling getAllClinicalDataInStudyUsingGET'
            );
        }
        if ($page_number !== null && $page_number < 0) {
            throw new \InvalidArgumentException('invalid value for "$page_number" when calling ClinicalDataApi.getAllClinicalDataInStudyUsingGET, must be bigger than or equal to 0.');
        }

        if ($page_size !== null && $page_size > 10000000) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling ClinicalDataApi.getAllClinicalDataInStudyUsingGET, must be smaller than or equal to 10000000.');
        }
        if ($page_size !== null && $page_size < 1) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling ClinicalDataApi.getAllClinicalDataInStudyUsingGET, must be bigger than or equal to 1.');
        }


        $resourcePath = '/studies/{studyId}/clinical-data';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($attribute_id !== null) {
            $queryParams['attributeId'] = ObjectSerializer::toQueryValue($attribute_id);
        }
        // query params
        if ($clinical_data_type !== null) {
            $queryParams['clinicalDataType'] = ObjectSerializer::toQueryValue($clinical_data_type);
        }
        // query params
        if ($direction !== null) {
            $queryParams['direction'] = ObjectSerializer::toQueryValue($direction);
        }
        // query params
        if ($page_number !== null) {
            $queryParams['pageNumber'] = ObjectSerializer::toQueryValue($page_number);
        }
        // query params
        if ($page_size !== null) {
            $queryParams['pageSize'] = ObjectSerializer::toQueryValue($page_size);
        }
        // query params
        if ($projection !== null) {
            $queryParams['projection'] = ObjectSerializer::toQueryValue($projection);
        }
        // query params
        if ($sort_by !== null) {
            $queryParams['sortBy'] = ObjectSerializer::toQueryValue($sort_by);
        }

        // path params
        if ($study_id !== null) {
            $resourcePath = str_replace(
                '{' . 'studyId' . '}',
                ObjectSerializer::toPathValue($study_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAllClinicalDataOfPatientInStudyUsingGET
     *
     * Get all clinical data of a patient in a study
     *
     * @param  string $patient_id Patient ID e.g. TCGA-OR-A5J2 (required)
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $attribute_id Attribute ID e.g. AGE (optional)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ClinicalData[]
     */
    public function getAllClinicalDataOfPatientInStudyUsingGET($patient_id, $study_id, $attribute_id = null, $direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        list($response) = $this->getAllClinicalDataOfPatientInStudyUsingGETWithHttpInfo($patient_id, $study_id, $attribute_id, $direction, $page_number, $page_size, $projection, $sort_by);
        return $response;
    }

    /**
     * Operation getAllClinicalDataOfPatientInStudyUsingGETWithHttpInfo
     *
     * Get all clinical data of a patient in a study
     *
     * @param  string $patient_id Patient ID e.g. TCGA-OR-A5J2 (required)
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $attribute_id Attribute ID e.g. AGE (optional)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ClinicalData[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllClinicalDataOfPatientInStudyUsingGETWithHttpInfo($patient_id, $study_id, $attribute_id = null, $direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        $returnType = '\Swagger\Client\Model\ClinicalData[]';
        $request = $this->getAllClinicalDataOfPatientInStudyUsingGETRequest($patient_id, $study_id, $attribute_id, $direction, $page_number, $page_size, $projection, $sort_by);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ClinicalData[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAllClinicalDataOfPatientInStudyUsingGETAsync
     *
     * Get all clinical data of a patient in a study
     *
     * @param  string $patient_id Patient ID e.g. TCGA-OR-A5J2 (required)
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $attribute_id Attribute ID e.g. AGE (optional)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllClinicalDataOfPatientInStudyUsingGETAsync($patient_id, $study_id, $attribute_id = null, $direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        return $this->getAllClinicalDataOfPatientInStudyUsingGETAsyncWithHttpInfo($patient_id, $study_id, $attribute_id, $direction, $page_number, $page_size, $projection, $sort_by)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllClinicalDataOfPatientInStudyUsingGETAsyncWithHttpInfo
     *
     * Get all clinical data of a patient in a study
     *
     * @param  string $patient_id Patient ID e.g. TCGA-OR-A5J2 (required)
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $attribute_id Attribute ID e.g. AGE (optional)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllClinicalDataOfPatientInStudyUsingGETAsyncWithHttpInfo($patient_id, $study_id, $attribute_id = null, $direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        $returnType = '\Swagger\Client\Model\ClinicalData[]';
        $request = $this->getAllClinicalDataOfPatientInStudyUsingGETRequest($patient_id, $study_id, $attribute_id, $direction, $page_number, $page_size, $projection, $sort_by);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllClinicalDataOfPatientInStudyUsingGET'
     *
     * @param  string $patient_id Patient ID e.g. TCGA-OR-A5J2 (required)
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $attribute_id Attribute ID e.g. AGE (optional)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAllClinicalDataOfPatientInStudyUsingGETRequest($patient_id, $study_id, $attribute_id = null, $direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        // verify the required parameter 'patient_id' is set
        if ($patient_id === null || (is_array($patient_id) && count($patient_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $patient_id when calling getAllClinicalDataOfPatientInStudyUsingGET'
            );
        }
        // verify the required parameter 'study_id' is set
        if ($study_id === null || (is_array($study_id) && count($study_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $study_id when calling getAllClinicalDataOfPatientInStudyUsingGET'
            );
        }
        if ($page_number !== null && $page_number < 0) {
            throw new \InvalidArgumentException('invalid value for "$page_number" when calling ClinicalDataApi.getAllClinicalDataOfPatientInStudyUsingGET, must be bigger than or equal to 0.');
        }

        if ($page_size !== null && $page_size > 10000000) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling ClinicalDataApi.getAllClinicalDataOfPatientInStudyUsingGET, must be smaller than or equal to 10000000.');
        }
        if ($page_size !== null && $page_size < 1) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling ClinicalDataApi.getAllClinicalDataOfPatientInStudyUsingGET, must be bigger than or equal to 1.');
        }


        $resourcePath = '/studies/{studyId}/patients/{patientId}/clinical-data';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($attribute_id !== null) {
            $queryParams['attributeId'] = ObjectSerializer::toQueryValue($attribute_id);
        }
        // query params
        if ($direction !== null) {
            $queryParams['direction'] = ObjectSerializer::toQueryValue($direction);
        }
        // query params
        if ($page_number !== null) {
            $queryParams['pageNumber'] = ObjectSerializer::toQueryValue($page_number);
        }
        // query params
        if ($page_size !== null) {
            $queryParams['pageSize'] = ObjectSerializer::toQueryValue($page_size);
        }
        // query params
        if ($projection !== null) {
            $queryParams['projection'] = ObjectSerializer::toQueryValue($projection);
        }
        // query params
        if ($sort_by !== null) {
            $queryParams['sortBy'] = ObjectSerializer::toQueryValue($sort_by);
        }

        // path params
        if ($patient_id !== null) {
            $resourcePath = str_replace(
                '{' . 'patientId' . '}',
                ObjectSerializer::toPathValue($patient_id),
                $resourcePath
            );
        }
        // path params
        if ($study_id !== null) {
            $resourcePath = str_replace(
                '{' . 'studyId' . '}',
                ObjectSerializer::toPathValue($study_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAllClinicalDataOfSampleInStudyUsingGET
     *
     * Get all clinical data of a sample in a study
     *
     * @param  string $sample_id Sample ID e.g. TCGA-OR-A5J2-01 (required)
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $attribute_id Attribute ID e.g. CANCER_TYPE (optional)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ClinicalData[]
     */
    public function getAllClinicalDataOfSampleInStudyUsingGET($sample_id, $study_id, $attribute_id = null, $direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        list($response) = $this->getAllClinicalDataOfSampleInStudyUsingGETWithHttpInfo($sample_id, $study_id, $attribute_id, $direction, $page_number, $page_size, $projection, $sort_by);
        return $response;
    }

    /**
     * Operation getAllClinicalDataOfSampleInStudyUsingGETWithHttpInfo
     *
     * Get all clinical data of a sample in a study
     *
     * @param  string $sample_id Sample ID e.g. TCGA-OR-A5J2-01 (required)
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $attribute_id Attribute ID e.g. CANCER_TYPE (optional)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ClinicalData[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllClinicalDataOfSampleInStudyUsingGETWithHttpInfo($sample_id, $study_id, $attribute_id = null, $direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        $returnType = '\Swagger\Client\Model\ClinicalData[]';
        $request = $this->getAllClinicalDataOfSampleInStudyUsingGETRequest($sample_id, $study_id, $attribute_id, $direction, $page_number, $page_size, $projection, $sort_by);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ClinicalData[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAllClinicalDataOfSampleInStudyUsingGETAsync
     *
     * Get all clinical data of a sample in a study
     *
     * @param  string $sample_id Sample ID e.g. TCGA-OR-A5J2-01 (required)
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $attribute_id Attribute ID e.g. CANCER_TYPE (optional)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllClinicalDataOfSampleInStudyUsingGETAsync($sample_id, $study_id, $attribute_id = null, $direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        return $this->getAllClinicalDataOfSampleInStudyUsingGETAsyncWithHttpInfo($sample_id, $study_id, $attribute_id, $direction, $page_number, $page_size, $projection, $sort_by)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllClinicalDataOfSampleInStudyUsingGETAsyncWithHttpInfo
     *
     * Get all clinical data of a sample in a study
     *
     * @param  string $sample_id Sample ID e.g. TCGA-OR-A5J2-01 (required)
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $attribute_id Attribute ID e.g. CANCER_TYPE (optional)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllClinicalDataOfSampleInStudyUsingGETAsyncWithHttpInfo($sample_id, $study_id, $attribute_id = null, $direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        $returnType = '\Swagger\Client\Model\ClinicalData[]';
        $request = $this->getAllClinicalDataOfSampleInStudyUsingGETRequest($sample_id, $study_id, $attribute_id, $direction, $page_number, $page_size, $projection, $sort_by);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllClinicalDataOfSampleInStudyUsingGET'
     *
     * @param  string $sample_id Sample ID e.g. TCGA-OR-A5J2-01 (required)
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     * @param  string $attribute_id Attribute ID e.g. CANCER_TYPE (optional)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAllClinicalDataOfSampleInStudyUsingGETRequest($sample_id, $study_id, $attribute_id = null, $direction = 'ASC', $page_number = '0', $page_size = '10000000', $projection = 'SUMMARY', $sort_by = null)
    {
        // verify the required parameter 'sample_id' is set
        if ($sample_id === null || (is_array($sample_id) && count($sample_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sample_id when calling getAllClinicalDataOfSampleInStudyUsingGET'
            );
        }
        // verify the required parameter 'study_id' is set
        if ($study_id === null || (is_array($study_id) && count($study_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $study_id when calling getAllClinicalDataOfSampleInStudyUsingGET'
            );
        }
        if ($page_number !== null && $page_number < 0) {
            throw new \InvalidArgumentException('invalid value for "$page_number" when calling ClinicalDataApi.getAllClinicalDataOfSampleInStudyUsingGET, must be bigger than or equal to 0.');
        }

        if ($page_size !== null && $page_size > 10000000) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling ClinicalDataApi.getAllClinicalDataOfSampleInStudyUsingGET, must be smaller than or equal to 10000000.');
        }
        if ($page_size !== null && $page_size < 1) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling ClinicalDataApi.getAllClinicalDataOfSampleInStudyUsingGET, must be bigger than or equal to 1.');
        }


        $resourcePath = '/studies/{studyId}/samples/{sampleId}/clinical-data';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($attribute_id !== null) {
            $queryParams['attributeId'] = ObjectSerializer::toQueryValue($attribute_id);
        }
        // query params
        if ($direction !== null) {
            $queryParams['direction'] = ObjectSerializer::toQueryValue($direction);
        }
        // query params
        if ($page_number !== null) {
            $queryParams['pageNumber'] = ObjectSerializer::toQueryValue($page_number);
        }
        // query params
        if ($page_size !== null) {
            $queryParams['pageSize'] = ObjectSerializer::toQueryValue($page_size);
        }
        // query params
        if ($projection !== null) {
            $queryParams['projection'] = ObjectSerializer::toQueryValue($projection);
        }
        // query params
        if ($sort_by !== null) {
            $queryParams['sortBy'] = ObjectSerializer::toQueryValue($sort_by);
        }

        // path params
        if ($sample_id !== null) {
            $resourcePath = str_replace(
                '{' . 'sampleId' . '}',
                ObjectSerializer::toPathValue($sample_id),
                $resourcePath
            );
        }
        // path params
        if ($study_id !== null) {
            $resourcePath = str_replace(
                '{' . 'studyId' . '}',
                ObjectSerializer::toPathValue($study_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
