<?php
/**
 * DiscreteCopyNumberAlterationsApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * cBioPortal web Public API [Beta]
 *
 * A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.
 *
 * OpenAPI spec version: 1.0
 * Contact: cbioportal@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * DiscreteCopyNumberAlterationsApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DiscreteCopyNumberAlterationsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation fetchDiscreteCopyNumbersInMolecularProfileUsingPOST
     *
     * Fetch discrete copy number alterations in a molecular profile by sample ID
     *
     * @param  \Swagger\Client\Model\DiscreteCopyNumberFilter $discrete_copy_number_filter List of Sample IDs/Sample List ID and Entrez Gene IDs (required)
     * @param  string $molecular_profile_id Molecular Profile ID e.g. acc_tcga_gistic (required)
     * @param  string $discrete_copy_number_event_type Type of the copy number event (optional, default to HOMDEL_AND_AMP)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\DiscreteCopyNumberData[]
     */
    public function fetchDiscreteCopyNumbersInMolecularProfileUsingPOST($discrete_copy_number_filter, $molecular_profile_id, $discrete_copy_number_event_type = 'HOMDEL_AND_AMP', $projection = 'SUMMARY')
    {
        list($response) = $this->fetchDiscreteCopyNumbersInMolecularProfileUsingPOSTWithHttpInfo($discrete_copy_number_filter, $molecular_profile_id, $discrete_copy_number_event_type, $projection);
        return $response;
    }

    /**
     * Operation fetchDiscreteCopyNumbersInMolecularProfileUsingPOSTWithHttpInfo
     *
     * Fetch discrete copy number alterations in a molecular profile by sample ID
     *
     * @param  \Swagger\Client\Model\DiscreteCopyNumberFilter $discrete_copy_number_filter List of Sample IDs/Sample List ID and Entrez Gene IDs (required)
     * @param  string $molecular_profile_id Molecular Profile ID e.g. acc_tcga_gistic (required)
     * @param  string $discrete_copy_number_event_type Type of the copy number event (optional, default to HOMDEL_AND_AMP)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\DiscreteCopyNumberData[], HTTP status code, HTTP response headers (array of strings)
     */
    public function fetchDiscreteCopyNumbersInMolecularProfileUsingPOSTWithHttpInfo($discrete_copy_number_filter, $molecular_profile_id, $discrete_copy_number_event_type = 'HOMDEL_AND_AMP', $projection = 'SUMMARY')
    {
        $returnType = '\Swagger\Client\Model\DiscreteCopyNumberData[]';
        $request = $this->fetchDiscreteCopyNumbersInMolecularProfileUsingPOSTRequest($discrete_copy_number_filter, $molecular_profile_id, $discrete_copy_number_event_type, $projection);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\DiscreteCopyNumberData[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation fetchDiscreteCopyNumbersInMolecularProfileUsingPOSTAsync
     *
     * Fetch discrete copy number alterations in a molecular profile by sample ID
     *
     * @param  \Swagger\Client\Model\DiscreteCopyNumberFilter $discrete_copy_number_filter List of Sample IDs/Sample List ID and Entrez Gene IDs (required)
     * @param  string $molecular_profile_id Molecular Profile ID e.g. acc_tcga_gistic (required)
     * @param  string $discrete_copy_number_event_type Type of the copy number event (optional, default to HOMDEL_AND_AMP)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function fetchDiscreteCopyNumbersInMolecularProfileUsingPOSTAsync($discrete_copy_number_filter, $molecular_profile_id, $discrete_copy_number_event_type = 'HOMDEL_AND_AMP', $projection = 'SUMMARY')
    {
        return $this->fetchDiscreteCopyNumbersInMolecularProfileUsingPOSTAsyncWithHttpInfo($discrete_copy_number_filter, $molecular_profile_id, $discrete_copy_number_event_type, $projection)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation fetchDiscreteCopyNumbersInMolecularProfileUsingPOSTAsyncWithHttpInfo
     *
     * Fetch discrete copy number alterations in a molecular profile by sample ID
     *
     * @param  \Swagger\Client\Model\DiscreteCopyNumberFilter $discrete_copy_number_filter List of Sample IDs/Sample List ID and Entrez Gene IDs (required)
     * @param  string $molecular_profile_id Molecular Profile ID e.g. acc_tcga_gistic (required)
     * @param  string $discrete_copy_number_event_type Type of the copy number event (optional, default to HOMDEL_AND_AMP)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function fetchDiscreteCopyNumbersInMolecularProfileUsingPOSTAsyncWithHttpInfo($discrete_copy_number_filter, $molecular_profile_id, $discrete_copy_number_event_type = 'HOMDEL_AND_AMP', $projection = 'SUMMARY')
    {
        $returnType = '\Swagger\Client\Model\DiscreteCopyNumberData[]';
        $request = $this->fetchDiscreteCopyNumbersInMolecularProfileUsingPOSTRequest($discrete_copy_number_filter, $molecular_profile_id, $discrete_copy_number_event_type, $projection);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'fetchDiscreteCopyNumbersInMolecularProfileUsingPOST'
     *
     * @param  \Swagger\Client\Model\DiscreteCopyNumberFilter $discrete_copy_number_filter List of Sample IDs/Sample List ID and Entrez Gene IDs (required)
     * @param  string $molecular_profile_id Molecular Profile ID e.g. acc_tcga_gistic (required)
     * @param  string $discrete_copy_number_event_type Type of the copy number event (optional, default to HOMDEL_AND_AMP)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function fetchDiscreteCopyNumbersInMolecularProfileUsingPOSTRequest($discrete_copy_number_filter, $molecular_profile_id, $discrete_copy_number_event_type = 'HOMDEL_AND_AMP', $projection = 'SUMMARY')
    {
        // verify the required parameter 'discrete_copy_number_filter' is set
        if ($discrete_copy_number_filter === null || (is_array($discrete_copy_number_filter) && count($discrete_copy_number_filter) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $discrete_copy_number_filter when calling fetchDiscreteCopyNumbersInMolecularProfileUsingPOST'
            );
        }
        // verify the required parameter 'molecular_profile_id' is set
        if ($molecular_profile_id === null || (is_array($molecular_profile_id) && count($molecular_profile_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $molecular_profile_id when calling fetchDiscreteCopyNumbersInMolecularProfileUsingPOST'
            );
        }

        $resourcePath = '/molecular-profiles/{molecularProfileId}/discrete-copy-number/fetch';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($discrete_copy_number_event_type !== null) {
            $queryParams['discreteCopyNumberEventType'] = ObjectSerializer::toQueryValue($discrete_copy_number_event_type);
        }
        // query params
        if ($projection !== null) {
            $queryParams['projection'] = ObjectSerializer::toQueryValue($projection);
        }

        // path params
        if ($molecular_profile_id !== null) {
            $resourcePath = str_replace(
                '{' . 'molecularProfileId' . '}',
                ObjectSerializer::toPathValue($molecular_profile_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($discrete_copy_number_filter)) {
            $_tempBody = $discrete_copy_number_filter;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getDiscreteCopyNumbersInMolecularProfileUsingGET
     *
     * Get discrete copy number alterations in a molecular profile
     *
     * @param  string $molecular_profile_id Molecular Profile ID e.g. acc_tcga_gistic (required)
     * @param  string $sample_list_id Sample List ID e.g. acc_tcga_all (required)
     * @param  string $discrete_copy_number_event_type Type of the copy number event (optional, default to HOMDEL_AND_AMP)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\DiscreteCopyNumberData[]
     */
    public function getDiscreteCopyNumbersInMolecularProfileUsingGET($molecular_profile_id, $sample_list_id, $discrete_copy_number_event_type = 'HOMDEL_AND_AMP', $projection = 'SUMMARY')
    {
        list($response) = $this->getDiscreteCopyNumbersInMolecularProfileUsingGETWithHttpInfo($molecular_profile_id, $sample_list_id, $discrete_copy_number_event_type, $projection);
        return $response;
    }

    /**
     * Operation getDiscreteCopyNumbersInMolecularProfileUsingGETWithHttpInfo
     *
     * Get discrete copy number alterations in a molecular profile
     *
     * @param  string $molecular_profile_id Molecular Profile ID e.g. acc_tcga_gistic (required)
     * @param  string $sample_list_id Sample List ID e.g. acc_tcga_all (required)
     * @param  string $discrete_copy_number_event_type Type of the copy number event (optional, default to HOMDEL_AND_AMP)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\DiscreteCopyNumberData[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getDiscreteCopyNumbersInMolecularProfileUsingGETWithHttpInfo($molecular_profile_id, $sample_list_id, $discrete_copy_number_event_type = 'HOMDEL_AND_AMP', $projection = 'SUMMARY')
    {
        $returnType = '\Swagger\Client\Model\DiscreteCopyNumberData[]';
        $request = $this->getDiscreteCopyNumbersInMolecularProfileUsingGETRequest($molecular_profile_id, $sample_list_id, $discrete_copy_number_event_type, $projection);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\DiscreteCopyNumberData[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getDiscreteCopyNumbersInMolecularProfileUsingGETAsync
     *
     * Get discrete copy number alterations in a molecular profile
     *
     * @param  string $molecular_profile_id Molecular Profile ID e.g. acc_tcga_gistic (required)
     * @param  string $sample_list_id Sample List ID e.g. acc_tcga_all (required)
     * @param  string $discrete_copy_number_event_type Type of the copy number event (optional, default to HOMDEL_AND_AMP)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDiscreteCopyNumbersInMolecularProfileUsingGETAsync($molecular_profile_id, $sample_list_id, $discrete_copy_number_event_type = 'HOMDEL_AND_AMP', $projection = 'SUMMARY')
    {
        return $this->getDiscreteCopyNumbersInMolecularProfileUsingGETAsyncWithHttpInfo($molecular_profile_id, $sample_list_id, $discrete_copy_number_event_type, $projection)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getDiscreteCopyNumbersInMolecularProfileUsingGETAsyncWithHttpInfo
     *
     * Get discrete copy number alterations in a molecular profile
     *
     * @param  string $molecular_profile_id Molecular Profile ID e.g. acc_tcga_gistic (required)
     * @param  string $sample_list_id Sample List ID e.g. acc_tcga_all (required)
     * @param  string $discrete_copy_number_event_type Type of the copy number event (optional, default to HOMDEL_AND_AMP)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDiscreteCopyNumbersInMolecularProfileUsingGETAsyncWithHttpInfo($molecular_profile_id, $sample_list_id, $discrete_copy_number_event_type = 'HOMDEL_AND_AMP', $projection = 'SUMMARY')
    {
        $returnType = '\Swagger\Client\Model\DiscreteCopyNumberData[]';
        $request = $this->getDiscreteCopyNumbersInMolecularProfileUsingGETRequest($molecular_profile_id, $sample_list_id, $discrete_copy_number_event_type, $projection);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getDiscreteCopyNumbersInMolecularProfileUsingGET'
     *
     * @param  string $molecular_profile_id Molecular Profile ID e.g. acc_tcga_gistic (required)
     * @param  string $sample_list_id Sample List ID e.g. acc_tcga_all (required)
     * @param  string $discrete_copy_number_event_type Type of the copy number event (optional, default to HOMDEL_AND_AMP)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getDiscreteCopyNumbersInMolecularProfileUsingGETRequest($molecular_profile_id, $sample_list_id, $discrete_copy_number_event_type = 'HOMDEL_AND_AMP', $projection = 'SUMMARY')
    {
        // verify the required parameter 'molecular_profile_id' is set
        if ($molecular_profile_id === null || (is_array($molecular_profile_id) && count($molecular_profile_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $molecular_profile_id when calling getDiscreteCopyNumbersInMolecularProfileUsingGET'
            );
        }
        // verify the required parameter 'sample_list_id' is set
        if ($sample_list_id === null || (is_array($sample_list_id) && count($sample_list_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sample_list_id when calling getDiscreteCopyNumbersInMolecularProfileUsingGET'
            );
        }

        $resourcePath = '/molecular-profiles/{molecularProfileId}/discrete-copy-number';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($discrete_copy_number_event_type !== null) {
            $queryParams['discreteCopyNumberEventType'] = ObjectSerializer::toQueryValue($discrete_copy_number_event_type);
        }
        // query params
        if ($projection !== null) {
            $queryParams['projection'] = ObjectSerializer::toQueryValue($projection);
        }
        // query params
        if ($sample_list_id !== null) {
            $queryParams['sampleListId'] = ObjectSerializer::toQueryValue($sample_list_id);
        }

        // path params
        if ($molecular_profile_id !== null) {
            $resourcePath = str_replace(
                '{' . 'molecularProfileId' . '}',
                ObjectSerializer::toPathValue($molecular_profile_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
