<?php
/**
 * StudiesApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * cBioPortal web Public API [Beta]
 *
 * A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.
 *
 * OpenAPI spec version: 1.0
 * Contact: cbioportal@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * StudiesApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StudiesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation fetchStudiesUsingPOST
     *
     * Fetch studies by IDs
     *
     * @param  string[] $study_ids List of Study IDs (required)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\CancerStudy[]
     */
    public function fetchStudiesUsingPOST($study_ids, $projection = 'SUMMARY')
    {
        list($response) = $this->fetchStudiesUsingPOSTWithHttpInfo($study_ids, $projection);
        return $response;
    }

    /**
     * Operation fetchStudiesUsingPOSTWithHttpInfo
     *
     * Fetch studies by IDs
     *
     * @param  string[] $study_ids List of Study IDs (required)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\CancerStudy[], HTTP status code, HTTP response headers (array of strings)
     */
    public function fetchStudiesUsingPOSTWithHttpInfo($study_ids, $projection = 'SUMMARY')
    {
        $returnType = '\Swagger\Client\Model\CancerStudy[]';
        $request = $this->fetchStudiesUsingPOSTRequest($study_ids, $projection);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\CancerStudy[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation fetchStudiesUsingPOSTAsync
     *
     * Fetch studies by IDs
     *
     * @param  string[] $study_ids List of Study IDs (required)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function fetchStudiesUsingPOSTAsync($study_ids, $projection = 'SUMMARY')
    {
        return $this->fetchStudiesUsingPOSTAsyncWithHttpInfo($study_ids, $projection)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation fetchStudiesUsingPOSTAsyncWithHttpInfo
     *
     * Fetch studies by IDs
     *
     * @param  string[] $study_ids List of Study IDs (required)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function fetchStudiesUsingPOSTAsyncWithHttpInfo($study_ids, $projection = 'SUMMARY')
    {
        $returnType = '\Swagger\Client\Model\CancerStudy[]';
        $request = $this->fetchStudiesUsingPOSTRequest($study_ids, $projection);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'fetchStudiesUsingPOST'
     *
     * @param  string[] $study_ids List of Study IDs (required)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function fetchStudiesUsingPOSTRequest($study_ids, $projection = 'SUMMARY')
    {
        // verify the required parameter 'study_ids' is set
        if ($study_ids === null || (is_array($study_ids) && count($study_ids) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $study_ids when calling fetchStudiesUsingPOST'
            );
        }

        $resourcePath = '/studies/fetch';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($projection !== null) {
            $queryParams['projection'] = ObjectSerializer::toQueryValue($projection);
        }


        // body params
        $_tempBody = null;
        if (isset($study_ids)) {
            $_tempBody = $study_ids;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAllStudiesUsingGET
     *
     * Get all studies
     *
     * @param  bool $authenticated authenticated (optional)
     * @param  string $authorities_0_authority authorities_0_authority (optional)
     * @param  map[string,string] $credentials credentials (optional)
     * @param  map[string,string] $details details (optional)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  string $keyword Search keyword that applies to name and cancer type of the studies (optional)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  map[string,string] $principal principal (optional)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\CancerStudy[]
     */
    public function getAllStudiesUsingGET($authenticated = null, $authorities_0_authority = null, $credentials = null, $details = null, $direction = 'ASC', $keyword = null, $page_number = '0', $page_size = '10000000', $principal = null, $projection = 'SUMMARY', $sort_by = null)
    {
        list($response) = $this->getAllStudiesUsingGETWithHttpInfo($authenticated, $authorities_0_authority, $credentials, $details, $direction, $keyword, $page_number, $page_size, $principal, $projection, $sort_by);
        return $response;
    }

    /**
     * Operation getAllStudiesUsingGETWithHttpInfo
     *
     * Get all studies
     *
     * @param  bool $authenticated (optional)
     * @param  string $authorities_0_authority (optional)
     * @param  map[string,string] $credentials (optional)
     * @param  map[string,string] $details (optional)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  string $keyword Search keyword that applies to name and cancer type of the studies (optional)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  map[string,string] $principal (optional)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\CancerStudy[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllStudiesUsingGETWithHttpInfo($authenticated = null, $authorities_0_authority = null, $credentials = null, $details = null, $direction = 'ASC', $keyword = null, $page_number = '0', $page_size = '10000000', $principal = null, $projection = 'SUMMARY', $sort_by = null)
    {
        $returnType = '\Swagger\Client\Model\CancerStudy[]';
        $request = $this->getAllStudiesUsingGETRequest($authenticated, $authorities_0_authority, $credentials, $details, $direction, $keyword, $page_number, $page_size, $principal, $projection, $sort_by);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\CancerStudy[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAllStudiesUsingGETAsync
     *
     * Get all studies
     *
     * @param  bool $authenticated (optional)
     * @param  string $authorities_0_authority (optional)
     * @param  map[string,string] $credentials (optional)
     * @param  map[string,string] $details (optional)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  string $keyword Search keyword that applies to name and cancer type of the studies (optional)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  map[string,string] $principal (optional)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllStudiesUsingGETAsync($authenticated = null, $authorities_0_authority = null, $credentials = null, $details = null, $direction = 'ASC', $keyword = null, $page_number = '0', $page_size = '10000000', $principal = null, $projection = 'SUMMARY', $sort_by = null)
    {
        return $this->getAllStudiesUsingGETAsyncWithHttpInfo($authenticated, $authorities_0_authority, $credentials, $details, $direction, $keyword, $page_number, $page_size, $principal, $projection, $sort_by)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllStudiesUsingGETAsyncWithHttpInfo
     *
     * Get all studies
     *
     * @param  bool $authenticated (optional)
     * @param  string $authorities_0_authority (optional)
     * @param  map[string,string] $credentials (optional)
     * @param  map[string,string] $details (optional)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  string $keyword Search keyword that applies to name and cancer type of the studies (optional)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  map[string,string] $principal (optional)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllStudiesUsingGETAsyncWithHttpInfo($authenticated = null, $authorities_0_authority = null, $credentials = null, $details = null, $direction = 'ASC', $keyword = null, $page_number = '0', $page_size = '10000000', $principal = null, $projection = 'SUMMARY', $sort_by = null)
    {
        $returnType = '\Swagger\Client\Model\CancerStudy[]';
        $request = $this->getAllStudiesUsingGETRequest($authenticated, $authorities_0_authority, $credentials, $details, $direction, $keyword, $page_number, $page_size, $principal, $projection, $sort_by);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllStudiesUsingGET'
     *
     * @param  bool $authenticated (optional)
     * @param  string $authorities_0_authority (optional)
     * @param  map[string,string] $credentials (optional)
     * @param  map[string,string] $details (optional)
     * @param  string $direction Direction of the sort (optional, default to ASC)
     * @param  string $keyword Search keyword that applies to name and cancer type of the studies (optional)
     * @param  int $page_number Page number of the result list (optional, default to 0)
     * @param  int $page_size Page size of the result list (optional, default to 10000000)
     * @param  map[string,string] $principal (optional)
     * @param  string $projection Level of detail of the response (optional, default to SUMMARY)
     * @param  string $sort_by Name of the property that the result list is sorted by (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAllStudiesUsingGETRequest($authenticated = null, $authorities_0_authority = null, $credentials = null, $details = null, $direction = 'ASC', $keyword = null, $page_number = '0', $page_size = '10000000', $principal = null, $projection = 'SUMMARY', $sort_by = null)
    {
        if ($page_number !== null && $page_number < 0) {
            throw new \InvalidArgumentException('invalid value for "$page_number" when calling StudiesApi.getAllStudiesUsingGET, must be bigger than or equal to 0.');
        }

        if ($page_size !== null && $page_size > 10000000) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling StudiesApi.getAllStudiesUsingGET, must be smaller than or equal to 10000000.');
        }
        if ($page_size !== null && $page_size < 1) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling StudiesApi.getAllStudiesUsingGET, must be bigger than or equal to 1.');
        }


        $resourcePath = '/studies';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($authenticated !== null) {
            $queryParams['authenticated'] = ObjectSerializer::toQueryValue($authenticated);
        }
        // query params
        if ($authorities_0_authority !== null) {
            $queryParams['authorities[0].authority'] = ObjectSerializer::toQueryValue($authorities_0_authority);
        }
        // query params
        if ($credentials !== null) {
            $queryParams['credentials'] = ObjectSerializer::toQueryValue($credentials);
        }
        // query params
        if ($details !== null) {
            $queryParams['details'] = ObjectSerializer::toQueryValue($details);
        }
        // query params
        if ($direction !== null) {
            $queryParams['direction'] = ObjectSerializer::toQueryValue($direction);
        }
        // query params
        if ($keyword !== null) {
            $queryParams['keyword'] = ObjectSerializer::toQueryValue($keyword);
        }
        // query params
        if ($page_number !== null) {
            $queryParams['pageNumber'] = ObjectSerializer::toQueryValue($page_number);
        }
        // query params
        if ($page_size !== null) {
            $queryParams['pageSize'] = ObjectSerializer::toQueryValue($page_size);
        }
        // query params
        if ($principal !== null) {
            $queryParams['principal'] = ObjectSerializer::toQueryValue($principal);
        }
        // query params
        if ($projection !== null) {
            $queryParams['projection'] = ObjectSerializer::toQueryValue($projection);
        }
        // query params
        if ($sort_by !== null) {
            $queryParams['sortBy'] = ObjectSerializer::toQueryValue($sort_by);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getStudyUsingGET
     *
     * Get a study
     *
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\CancerStudy
     */
    public function getStudyUsingGET($study_id)
    {
        list($response) = $this->getStudyUsingGETWithHttpInfo($study_id);
        return $response;
    }

    /**
     * Operation getStudyUsingGETWithHttpInfo
     *
     * Get a study
     *
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\CancerStudy, HTTP status code, HTTP response headers (array of strings)
     */
    public function getStudyUsingGETWithHttpInfo($study_id)
    {
        $returnType = '\Swagger\Client\Model\CancerStudy';
        $request = $this->getStudyUsingGETRequest($study_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\CancerStudy',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getStudyUsingGETAsync
     *
     * Get a study
     *
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStudyUsingGETAsync($study_id)
    {
        return $this->getStudyUsingGETAsyncWithHttpInfo($study_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getStudyUsingGETAsyncWithHttpInfo
     *
     * Get a study
     *
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStudyUsingGETAsyncWithHttpInfo($study_id)
    {
        $returnType = '\Swagger\Client\Model\CancerStudy';
        $request = $this->getStudyUsingGETRequest($study_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getStudyUsingGET'
     *
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getStudyUsingGETRequest($study_id)
    {
        // verify the required parameter 'study_id' is set
        if ($study_id === null || (is_array($study_id) && count($study_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $study_id when calling getStudyUsingGET'
            );
        }

        $resourcePath = '/studies/{studyId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($study_id !== null) {
            $resourcePath = str_replace(
                '{' . 'studyId' . '}',
                ObjectSerializer::toPathValue($study_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getTagsForMultipleStudiesUsingPOST
     *
     * Get the study tags by IDs
     *
     * @param  string[] $study_ids List of Study IDs (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\CancerStudyTags[]
     */
    public function getTagsForMultipleStudiesUsingPOST($study_ids)
    {
        list($response) = $this->getTagsForMultipleStudiesUsingPOSTWithHttpInfo($study_ids);
        return $response;
    }

    /**
     * Operation getTagsForMultipleStudiesUsingPOSTWithHttpInfo
     *
     * Get the study tags by IDs
     *
     * @param  string[] $study_ids List of Study IDs (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\CancerStudyTags[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getTagsForMultipleStudiesUsingPOSTWithHttpInfo($study_ids)
    {
        $returnType = '\Swagger\Client\Model\CancerStudyTags[]';
        $request = $this->getTagsForMultipleStudiesUsingPOSTRequest($study_ids);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\CancerStudyTags[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getTagsForMultipleStudiesUsingPOSTAsync
     *
     * Get the study tags by IDs
     *
     * @param  string[] $study_ids List of Study IDs (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTagsForMultipleStudiesUsingPOSTAsync($study_ids)
    {
        return $this->getTagsForMultipleStudiesUsingPOSTAsyncWithHttpInfo($study_ids)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getTagsForMultipleStudiesUsingPOSTAsyncWithHttpInfo
     *
     * Get the study tags by IDs
     *
     * @param  string[] $study_ids List of Study IDs (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTagsForMultipleStudiesUsingPOSTAsyncWithHttpInfo($study_ids)
    {
        $returnType = '\Swagger\Client\Model\CancerStudyTags[]';
        $request = $this->getTagsForMultipleStudiesUsingPOSTRequest($study_ids);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getTagsForMultipleStudiesUsingPOST'
     *
     * @param  string[] $study_ids List of Study IDs (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getTagsForMultipleStudiesUsingPOSTRequest($study_ids)
    {
        // verify the required parameter 'study_ids' is set
        if ($study_ids === null || (is_array($study_ids) && count($study_ids) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $study_ids when calling getTagsForMultipleStudiesUsingPOST'
            );
        }

        $resourcePath = '/studies/tags/fetch';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($study_ids)) {
            $_tempBody = $study_ids;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getTagsUsingGET
     *
     * Get the tags of a study
     *
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function getTagsUsingGET($study_id)
    {
        list($response) = $this->getTagsUsingGETWithHttpInfo($study_id);
        return $response;
    }

    /**
     * Operation getTagsUsingGETWithHttpInfo
     *
     * Get the tags of a study
     *
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function getTagsUsingGETWithHttpInfo($study_id)
    {
        $returnType = 'object';
        $request = $this->getTagsUsingGETRequest($study_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getTagsUsingGETAsync
     *
     * Get the tags of a study
     *
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTagsUsingGETAsync($study_id)
    {
        return $this->getTagsUsingGETAsyncWithHttpInfo($study_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getTagsUsingGETAsyncWithHttpInfo
     *
     * Get the tags of a study
     *
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTagsUsingGETAsyncWithHttpInfo($study_id)
    {
        $returnType = 'object';
        $request = $this->getTagsUsingGETRequest($study_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getTagsUsingGET'
     *
     * @param  string $study_id Study ID e.g. acc_tcga (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getTagsUsingGETRequest($study_id)
    {
        // verify the required parameter 'study_id' is set
        if ($study_id === null || (is_array($study_id) && count($study_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $study_id when calling getTagsUsingGET'
            );
        }

        $resourcePath = '/studies/{studyId}/tags';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($study_id !== null) {
            $resourcePath = str_replace(
                '{' . 'studyId' . '}',
                ObjectSerializer::toPathValue($study_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
