<?php
/**
 * TreatmentsApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * cBioPortal web Public API [Beta]
 *
 * A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.
 *
 * OpenAPI spec version: 1.0
 * Contact: cbioportal@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * TreatmentsApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TreatmentsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getAllPatientTreatmentsUsingPOST
     *
     * Get all patient level treatments
     *
     * @param  \Swagger\Client\Model\StudyViewFilter $study_view_filter Study view filter (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\PatientTreatmentRow[]
     */
    public function getAllPatientTreatmentsUsingPOST($study_view_filter, $tier = 'Treatment')
    {
        list($response) = $this->getAllPatientTreatmentsUsingPOSTWithHttpInfo($study_view_filter, $tier);
        return $response;
    }

    /**
     * Operation getAllPatientTreatmentsUsingPOSTWithHttpInfo
     *
     * Get all patient level treatments
     *
     * @param  \Swagger\Client\Model\StudyViewFilter $study_view_filter Study view filter (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\PatientTreatmentRow[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllPatientTreatmentsUsingPOSTWithHttpInfo($study_view_filter, $tier = 'Treatment')
    {
        $returnType = '\Swagger\Client\Model\PatientTreatmentRow[]';
        $request = $this->getAllPatientTreatmentsUsingPOSTRequest($study_view_filter, $tier);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\PatientTreatmentRow[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAllPatientTreatmentsUsingPOSTAsync
     *
     * Get all patient level treatments
     *
     * @param  \Swagger\Client\Model\StudyViewFilter $study_view_filter Study view filter (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllPatientTreatmentsUsingPOSTAsync($study_view_filter, $tier = 'Treatment')
    {
        return $this->getAllPatientTreatmentsUsingPOSTAsyncWithHttpInfo($study_view_filter, $tier)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllPatientTreatmentsUsingPOSTAsyncWithHttpInfo
     *
     * Get all patient level treatments
     *
     * @param  \Swagger\Client\Model\StudyViewFilter $study_view_filter Study view filter (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllPatientTreatmentsUsingPOSTAsyncWithHttpInfo($study_view_filter, $tier = 'Treatment')
    {
        $returnType = '\Swagger\Client\Model\PatientTreatmentRow[]';
        $request = $this->getAllPatientTreatmentsUsingPOSTRequest($study_view_filter, $tier);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllPatientTreatmentsUsingPOST'
     *
     * @param  \Swagger\Client\Model\StudyViewFilter $study_view_filter Study view filter (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAllPatientTreatmentsUsingPOSTRequest($study_view_filter, $tier = 'Treatment')
    {
        // verify the required parameter 'study_view_filter' is set
        if ($study_view_filter === null || (is_array($study_view_filter) && count($study_view_filter) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $study_view_filter when calling getAllPatientTreatmentsUsingPOST'
            );
        }

        $resourcePath = '/treatments/patient';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($tier !== null) {
            $queryParams['tier'] = ObjectSerializer::toQueryValue($tier);
        }


        // body params
        $_tempBody = null;
        if (isset($study_view_filter)) {
            $_tempBody = $study_view_filter;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAllSampleTreatmentsUsingPOST
     *
     * Get all sample level treatments
     *
     * @param  \Swagger\Client\Model\StudyViewFilter $study_view_filter Study view filter (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\SampleTreatmentRow[]
     */
    public function getAllSampleTreatmentsUsingPOST($study_view_filter, $tier = 'Treatment')
    {
        list($response) = $this->getAllSampleTreatmentsUsingPOSTWithHttpInfo($study_view_filter, $tier);
        return $response;
    }

    /**
     * Operation getAllSampleTreatmentsUsingPOSTWithHttpInfo
     *
     * Get all sample level treatments
     *
     * @param  \Swagger\Client\Model\StudyViewFilter $study_view_filter Study view filter (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\SampleTreatmentRow[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllSampleTreatmentsUsingPOSTWithHttpInfo($study_view_filter, $tier = 'Treatment')
    {
        $returnType = '\Swagger\Client\Model\SampleTreatmentRow[]';
        $request = $this->getAllSampleTreatmentsUsingPOSTRequest($study_view_filter, $tier);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\SampleTreatmentRow[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAllSampleTreatmentsUsingPOSTAsync
     *
     * Get all sample level treatments
     *
     * @param  \Swagger\Client\Model\StudyViewFilter $study_view_filter Study view filter (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllSampleTreatmentsUsingPOSTAsync($study_view_filter, $tier = 'Treatment')
    {
        return $this->getAllSampleTreatmentsUsingPOSTAsyncWithHttpInfo($study_view_filter, $tier)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllSampleTreatmentsUsingPOSTAsyncWithHttpInfo
     *
     * Get all sample level treatments
     *
     * @param  \Swagger\Client\Model\StudyViewFilter $study_view_filter Study view filter (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllSampleTreatmentsUsingPOSTAsyncWithHttpInfo($study_view_filter, $tier = 'Treatment')
    {
        $returnType = '\Swagger\Client\Model\SampleTreatmentRow[]';
        $request = $this->getAllSampleTreatmentsUsingPOSTRequest($study_view_filter, $tier);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllSampleTreatmentsUsingPOST'
     *
     * @param  \Swagger\Client\Model\StudyViewFilter $study_view_filter Study view filter (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAllSampleTreatmentsUsingPOSTRequest($study_view_filter, $tier = 'Treatment')
    {
        // verify the required parameter 'study_view_filter' is set
        if ($study_view_filter === null || (is_array($study_view_filter) && count($study_view_filter) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $study_view_filter when calling getAllSampleTreatmentsUsingPOST'
            );
        }

        $resourcePath = '/treatments/sample';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($tier !== null) {
            $queryParams['tier'] = ObjectSerializer::toQueryValue($tier);
        }


        // body params
        $_tempBody = null;
        if (isset($study_view_filter)) {
            $_tempBody = $study_view_filter;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getContainsSampleTreatmentDataUsingPOST
     *
     * Should sample level treatments be displayed
     *
     * @param  string[] $study_ids List of Study IDs (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return bool
     */
    public function getContainsSampleTreatmentDataUsingPOST($study_ids, $tier = 'Treatment')
    {
        list($response) = $this->getContainsSampleTreatmentDataUsingPOSTWithHttpInfo($study_ids, $tier);
        return $response;
    }

    /**
     * Operation getContainsSampleTreatmentDataUsingPOSTWithHttpInfo
     *
     * Should sample level treatments be displayed
     *
     * @param  string[] $study_ids List of Study IDs (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of bool, HTTP status code, HTTP response headers (array of strings)
     */
    public function getContainsSampleTreatmentDataUsingPOSTWithHttpInfo($study_ids, $tier = 'Treatment')
    {
        $returnType = 'bool';
        $request = $this->getContainsSampleTreatmentDataUsingPOSTRequest($study_ids, $tier);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'bool',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getContainsSampleTreatmentDataUsingPOSTAsync
     *
     * Should sample level treatments be displayed
     *
     * @param  string[] $study_ids List of Study IDs (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getContainsSampleTreatmentDataUsingPOSTAsync($study_ids, $tier = 'Treatment')
    {
        return $this->getContainsSampleTreatmentDataUsingPOSTAsyncWithHttpInfo($study_ids, $tier)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getContainsSampleTreatmentDataUsingPOSTAsyncWithHttpInfo
     *
     * Should sample level treatments be displayed
     *
     * @param  string[] $study_ids List of Study IDs (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getContainsSampleTreatmentDataUsingPOSTAsyncWithHttpInfo($study_ids, $tier = 'Treatment')
    {
        $returnType = 'bool';
        $request = $this->getContainsSampleTreatmentDataUsingPOSTRequest($study_ids, $tier);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getContainsSampleTreatmentDataUsingPOST'
     *
     * @param  string[] $study_ids List of Study IDs (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getContainsSampleTreatmentDataUsingPOSTRequest($study_ids, $tier = 'Treatment')
    {
        // verify the required parameter 'study_ids' is set
        if ($study_ids === null || (is_array($study_ids) && count($study_ids) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $study_ids when calling getContainsSampleTreatmentDataUsingPOST'
            );
        }

        $resourcePath = '/treatments/display-sample';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($tier !== null) {
            $queryParams['tier'] = ObjectSerializer::toQueryValue($tier);
        }


        // body params
        $_tempBody = null;
        if (isset($study_ids)) {
            $_tempBody = $study_ids;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getContainsTreatmentDataUsingPOST
     *
     * Should patient level treatments be displayed
     *
     * @param  string[] $study_ids List of Study IDs (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return bool
     */
    public function getContainsTreatmentDataUsingPOST($study_ids, $tier = 'Treatment')
    {
        list($response) = $this->getContainsTreatmentDataUsingPOSTWithHttpInfo($study_ids, $tier);
        return $response;
    }

    /**
     * Operation getContainsTreatmentDataUsingPOSTWithHttpInfo
     *
     * Should patient level treatments be displayed
     *
     * @param  string[] $study_ids List of Study IDs (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of bool, HTTP status code, HTTP response headers (array of strings)
     */
    public function getContainsTreatmentDataUsingPOSTWithHttpInfo($study_ids, $tier = 'Treatment')
    {
        $returnType = 'bool';
        $request = $this->getContainsTreatmentDataUsingPOSTRequest($study_ids, $tier);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'bool',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getContainsTreatmentDataUsingPOSTAsync
     *
     * Should patient level treatments be displayed
     *
     * @param  string[] $study_ids List of Study IDs (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getContainsTreatmentDataUsingPOSTAsync($study_ids, $tier = 'Treatment')
    {
        return $this->getContainsTreatmentDataUsingPOSTAsyncWithHttpInfo($study_ids, $tier)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getContainsTreatmentDataUsingPOSTAsyncWithHttpInfo
     *
     * Should patient level treatments be displayed
     *
     * @param  string[] $study_ids List of Study IDs (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getContainsTreatmentDataUsingPOSTAsyncWithHttpInfo($study_ids, $tier = 'Treatment')
    {
        $returnType = 'bool';
        $request = $this->getContainsTreatmentDataUsingPOSTRequest($study_ids, $tier);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getContainsTreatmentDataUsingPOST'
     *
     * @param  string[] $study_ids List of Study IDs (required)
     * @param  string $tier tier (optional, default to Treatment)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getContainsTreatmentDataUsingPOSTRequest($study_ids, $tier = 'Treatment')
    {
        // verify the required parameter 'study_ids' is set
        if ($study_ids === null || (is_array($study_ids) && count($study_ids) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $study_ids when calling getContainsTreatmentDataUsingPOST'
            );
        }

        $resourcePath = '/treatments/display-patient';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($tier !== null) {
            $queryParams['tier'] = ObjectSerializer::toQueryValue($tier);
        }


        // body params
        $_tempBody = null;
        if (isset($study_ids)) {
            $_tempBody = $study_ids;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
