<?php
/**
 * CancerStudyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * cBioPortal web Public API [Beta]
 *
 * A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.
 *
 * OpenAPI spec version: 1.0
 * Contact: cbioportal@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CancerStudyTest Class Doc Comment
 *
 * @category    Class
 * @description CancerStudy
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CancerStudyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CancerStudy"
     */
    public function testCancerStudy()
    {
    }

    /**
     * Test attribute "all_sample_count"
     */
    public function testPropertyAllSampleCount()
    {
    }

    /**
     * Test attribute "cancer_type"
     */
    public function testPropertyCancerType()
    {
    }

    /**
     * Test attribute "cancer_type_id"
     */
    public function testPropertyCancerTypeId()
    {
    }

    /**
     * Test attribute "citation"
     */
    public function testPropertyCitation()
    {
    }

    /**
     * Test attribute "cna_sample_count"
     */
    public function testPropertyCnaSampleCount()
    {
    }

    /**
     * Test attribute "complete_sample_count"
     */
    public function testPropertyCompleteSampleCount()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "groups"
     */
    public function testPropertyGroups()
    {
    }

    /**
     * Test attribute "import_date"
     */
    public function testPropertyImportDate()
    {
    }

    /**
     * Test attribute "mass_spectrometry_sample_count"
     */
    public function testPropertyMassSpectrometrySampleCount()
    {
    }

    /**
     * Test attribute "methylation_hm27_sample_count"
     */
    public function testPropertyMethylationHm27SampleCount()
    {
    }

    /**
     * Test attribute "mi_rna_sample_count"
     */
    public function testPropertyMiRnaSampleCount()
    {
    }

    /**
     * Test attribute "mrna_microarray_sample_count"
     */
    public function testPropertyMrnaMicroarraySampleCount()
    {
    }

    /**
     * Test attribute "mrna_rna_seq_sample_count"
     */
    public function testPropertyMrnaRnaSeqSampleCount()
    {
    }

    /**
     * Test attribute "mrna_rna_seq_v2_sample_count"
     */
    public function testPropertyMrnaRnaSeqV2SampleCount()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "pmid"
     */
    public function testPropertyPmid()
    {
    }

    /**
     * Test attribute "public_study"
     */
    public function testPropertyPublicStudy()
    {
    }

    /**
     * Test attribute "read_permission"
     */
    public function testPropertyReadPermission()
    {
    }

    /**
     * Test attribute "reference_genome"
     */
    public function testPropertyReferenceGenome()
    {
    }

    /**
     * Test attribute "rppa_sample_count"
     */
    public function testPropertyRppaSampleCount()
    {
    }

    /**
     * Test attribute "sequenced_sample_count"
     */
    public function testPropertySequencedSampleCount()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "study_id"
     */
    public function testPropertyStudyId()
    {
    }
}
