<?php
/**
 * MutationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * cBioPortal web Public API [Beta]
 *
 * A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.
 *
 * OpenAPI spec version: 1.0
 * Contact: cbioportal@googlegroups.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MutationTest Class Doc Comment
 *
 * @category    Class
 * @description Mutation
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MutationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Mutation"
     */
    public function testMutation()
    {
    }

    /**
     * Test attribute "allele_specific_copy_number"
     */
    public function testPropertyAlleleSpecificCopyNumber()
    {
    }

    /**
     * Test attribute "amino_acid_change"
     */
    public function testPropertyAminoAcidChange()
    {
    }

    /**
     * Test attribute "center"
     */
    public function testPropertyCenter()
    {
    }

    /**
     * Test attribute "chr"
     */
    public function testPropertyChr()
    {
    }

    /**
     * Test attribute "driver_filter"
     */
    public function testPropertyDriverFilter()
    {
    }

    /**
     * Test attribute "driver_filter_annotation"
     */
    public function testPropertyDriverFilterAnnotation()
    {
    }

    /**
     * Test attribute "driver_tiers_filter"
     */
    public function testPropertyDriverTiersFilter()
    {
    }

    /**
     * Test attribute "driver_tiers_filter_annotation"
     */
    public function testPropertyDriverTiersFilterAnnotation()
    {
    }

    /**
     * Test attribute "end_position"
     */
    public function testPropertyEndPosition()
    {
    }

    /**
     * Test attribute "entrez_gene_id"
     */
    public function testPropertyEntrezGeneId()
    {
    }

    /**
     * Test attribute "fis_value"
     */
    public function testPropertyFisValue()
    {
    }

    /**
     * Test attribute "functional_impact_score"
     */
    public function testPropertyFunctionalImpactScore()
    {
    }

    /**
     * Test attribute "gene"
     */
    public function testPropertyGene()
    {
    }

    /**
     * Test attribute "keyword"
     */
    public function testPropertyKeyword()
    {
    }

    /**
     * Test attribute "link_msa"
     */
    public function testPropertyLinkMsa()
    {
    }

    /**
     * Test attribute "link_pdb"
     */
    public function testPropertyLinkPdb()
    {
    }

    /**
     * Test attribute "link_xvar"
     */
    public function testPropertyLinkXvar()
    {
    }

    /**
     * Test attribute "molecular_profile_id"
     */
    public function testPropertyMolecularProfileId()
    {
    }

    /**
     * Test attribute "mutation_status"
     */
    public function testPropertyMutationStatus()
    {
    }

    /**
     * Test attribute "mutation_type"
     */
    public function testPropertyMutationType()
    {
    }

    /**
     * Test attribute "namespace_columns"
     */
    public function testPropertyNamespaceColumns()
    {
    }

    /**
     * Test attribute "ncbi_build"
     */
    public function testPropertyNcbiBuild()
    {
    }

    /**
     * Test attribute "normal_alt_count"
     */
    public function testPropertyNormalAltCount()
    {
    }

    /**
     * Test attribute "normal_ref_count"
     */
    public function testPropertyNormalRefCount()
    {
    }

    /**
     * Test attribute "patient_id"
     */
    public function testPropertyPatientId()
    {
    }

    /**
     * Test attribute "protein_change"
     */
    public function testPropertyProteinChange()
    {
    }

    /**
     * Test attribute "protein_pos_end"
     */
    public function testPropertyProteinPosEnd()
    {
    }

    /**
     * Test attribute "protein_pos_start"
     */
    public function testPropertyProteinPosStart()
    {
    }

    /**
     * Test attribute "reference_allele"
     */
    public function testPropertyReferenceAllele()
    {
    }

    /**
     * Test attribute "refseq_mrna_id"
     */
    public function testPropertyRefseqMrnaId()
    {
    }

    /**
     * Test attribute "sample_id"
     */
    public function testPropertySampleId()
    {
    }

    /**
     * Test attribute "start_position"
     */
    public function testPropertyStartPosition()
    {
    }

    /**
     * Test attribute "study_id"
     */
    public function testPropertyStudyId()
    {
    }

    /**
     * Test attribute "tumor_alt_count"
     */
    public function testPropertyTumorAltCount()
    {
    }

    /**
     * Test attribute "tumor_ref_count"
     */
    public function testPropertyTumorRefCount()
    {
    }

    /**
     * Test attribute "unique_patient_key"
     */
    public function testPropertyUniquePatientKey()
    {
    }

    /**
     * Test attribute "unique_sample_key"
     */
    public function testPropertyUniqueSampleKey()
    {
    }

    /**
     * Test attribute "validation_status"
     */
    public function testPropertyValidationStatus()
    {
    }

    /**
     * Test attribute "variant_allele"
     */
    public function testPropertyVariantAllele()
    {
    }

    /**
     * Test attribute "variant_type"
     */
    public function testPropertyVariantType()
    {
    }
}
